"""Stage 3: pairwise features for (query record, Source-1 entity) candidates.

Feature families
  * token alignment (Numba): soft token matching with a Levenshtein kernel over
    a per-country vocabulary; IDF mass of matched / unexplained tokens; the
    "sibling ratio" of unexplained tokens (see below); order inversions.
  * rapidfuzz string similarities (vectorised C++, multi-threaded cpdist) on
    names, glued names, aliases, addresses, streets, localities.
  * house-number arithmetic (numeric delta, digit subsequence, first/last digit)
  * legal form agreement, record flags, retrieval score/rank
  * label-free universe statistics (chain names, multi-tenant addresses, dups)

The sibling ratio of a token t in a universe/country is
      log((c_S2S3(t)+1) / (c_S1(t)+1)) - log(N_S2S3 / N_S1)
Hard-negative "sibling" businesses are generated by adding words that never
occur in the deduplicated reference (Source 1) - e.g. "northside", "eastgate",
"participations" - so their ratio is extreme.  It is computed without labels,
separately for every universe (train / test) and country, hence it transfers
to countries never seen in training (France).
"""
from __future__ import annotations

import numpy as np
import polars as pl
import pyarrow as pa
from numba import njit, prange
from rapidfuzz import fuzz, process
from rapidfuzz.distance import Indel, JaroWinkler, Levenshtein

from blocking import load_universe
from common import Timer, log

NORM_COLS = ["entity_id", "country", "src", "n_all", "n_core", "n_alt", "n_legal", "n_flags",
             "n_indic", "n_indic_hit", "a_all", "a_tok", "a_hn", "a_hnsfx", "a_street", "a_loc",
             "a_state", "a_unit", "a_flags"]

MAXTOK = 48
SIB_OFFSET = 2.0
# Universe-invariant token statistics.  The test universe differs from train in size
# (test US has half the entities of train US) and in distractor density, so every
# statistic must depend on relative frequencies only and must be too coarse for the
# trees to memorise per-token constants:
#   idf   = log(N1 / df1) (a relative frequency, invariant to universe size), rounded
#           to IDF_STEP and capped at IDF_CAP (all rare tokens look alike)
#   ratio = sibling statistic rounded to RATIO_STEP
#   u_*   = universe counts capped at U_CAP
# (v2 used idf / log(N1): a generic noise word such as "center" moved from 0.271 in
# train to 0.283 in test and the trees, which had memorised its exact value, scored
# true "... Center" records 0.99 in validation but 0.70 on test.)
IDF_STEP = 0.25
IDF_CAP = 9.0
RATIO_STEP = 0.5
U_CAP = 3
# Word behaviour (label-free, per universe and country).  For every record and its most
# likely Source-1 candidate (pruner argmax), each word of the record that the candidate's
# name does not contain is an "extra" word; we count how often records carrying it keep the
# candidate's house number (noise on a true match: "Regional Steel" -> "Regional Services",
# French "... et Fils"), shift it upward by 1..BH_UP_MAX (generated sibling business:
# "... Coastal", "... Distribution") or have no house number.  Validated on train labels:
# words with same-rate >= 0.7 are 91-98 % true matches, words with same-rate <= 0.1 are 0-5 %.
# The rates describe what a word *does* in its own universe, so they transfer to a country
# without labels (France), where the IDF-based word identity of US/India cannot.
BH_UP_MAX = 40
BH_MIN_N = 30          # rates of words seen fewer times are unknown (NaN)
BH_STEP = 0.1          # rates are rounded (no per-word constants to memorise)


# ----------------------------------------------------------------------------
# vocabulary / CSR token lists
# ----------------------------------------------------------------------------
class TokenSpace:
    """(country, token) vocabulary shared by S1 and query tables for one field.

    Built chunk-wise: only (record, token-hash) numpy arrays and the unique
    vocabulary are ever materialised, so memory stays low on ~12M records."""

    CHUNK = 2_000_000

    def __init__(self, s1: pl.DataFrame, q: pl.DataFrame, col: str, stat_col: str | None = None):
        stat_col = stat_col or col
        voc_parts = []
        r1, h1 = self._explode_all(s1, col, voc_parts)
        rq, hq = self._explode_all(q, col, voc_parts)
        voc = pl.concat(voc_parts).unique(subset="h").sort("h")
        del voc_parts
        self.hashes = voc["h"].to_numpy()
        self.V = len(self.hashes)
        arr = voc["t"].str.slice(0, 40).to_arrow().cast(pa.large_string())
        bufs = arr.buffers()
        offs = np.frombuffer(bufs[1], dtype=np.int64)[arr.offset: arr.offset + self.V + 1]
        self.voc_ptr = (offs - offs[0]).astype(np.int64)
        self.voc_buf = np.frombuffer(bufs[2], dtype=np.uint8)[offs[0]: offs[-1]].copy()
        self.is_num = voc["t"].str.contains(r"\d").to_numpy()
        self.country_of = voc["country"].to_numpy()
        del voc, arr, bufs
        self.s1_ptr, self.s1_ids = self._csr(r1, h1, s1.height)
        self.q_ptr, self.q_ids = self._csr(rq, hq, q.height)
        del r1, h1, rq, hq
        # statistics (document frequencies in S1 and in S2/S3)
        if stat_col != col:
            ids1 = self._ids(self._explode_all(s1, stat_col, None)[1])
            idsq = self._ids(self._explode_all(q, stat_col, None)[1])
        else:
            ids1, idsq = self.s1_ids, self.q_ids
        df1 = np.bincount(ids1[ids1 >= 0], minlength=self.V).astype(np.float64)
        c23 = np.bincount(idsq[idsq >= 0], minlength=self.V).astype(np.float64)
        del ids1, idsq
        n1 = dict(s1.group_by("country").len().iter_rows())
        nq = dict(q.group_by("country").len().iter_rows())
        cats, inv = np.unique(self.country_of, return_inverse=True)
        N1 = np.array([n1.get(c, 1) for c in cats], np.float64)[inv]
        NQ = np.array([nq.get(c, 1) for c in cats], np.float64)[inv]
        self.df1 = df1.astype(np.float32)
        raw_idf = np.log((N1 + 1.0) / (df1 + 1.0))
        self.idf = np.minimum(np.round(raw_idf / IDF_STEP) * IDF_STEP, IDF_CAP).astype(np.float32)
        self.ratio_raw = (np.log((c23 + 1.0) / (df1 + 1.0)) - np.log(NQ / N1)).astype(np.float32)
        # Shift-robust "sibling" statistic: every benign token maps to exactly 0;
        # only strongly over-represented tokens (raw > 2, i.e. >7x more frequent in
        # S2/S3 than expected) carry signal, in coarse steps.
        self.ratio = np.clip(np.round((self.ratio_raw - SIB_OFFSET) / RATIO_STEP) * RATIO_STEP,
                             0.0, 8.0).astype(np.float32)
        # statistics of the candidate pruner (candidates.py), which was trained on them
        self.idf_pruner = (raw_idf / np.log(N1 + 1.0)).astype(np.float32)
        self.ratio_pruner = np.clip(self.ratio_raw - SIB_OFFSET, 0.0, 8.0).astype(np.float32)

    def _explode_all(self, df, col, voc_parts):
        rs, hs = [], []
        for off in range(0, df.height, self.CHUNK):
            part = df.slice(off, self.CHUNK)
            ex = (part.select(pl.int_range(off, off + part.height, dtype=pl.Int64).alias("r"),
                              "country", pl.col(col).fill_null("").str.split(" ").alias("t"))
                  .explode("t")
                  .filter(pl.col("t").is_not_null() & (pl.col("t").str.len_chars() > 0))
                  .unique(subset=["r", "t"], maintain_order=True)
                  .with_columns(pl.concat_str(["country", "t"], separator="").hash(seed=11).alias("h")))
            if voc_parts is not None:
                voc_parts.append(ex.select("h", "country", "t").unique(subset="h"))
            rs.append(ex["r"].to_numpy())
            hs.append(ex["h"].to_numpy())
            del ex
        return np.concatenate(rs), np.concatenate(hs)

    def _ids(self, h):
        pos = np.searchsorted(self.hashes, h)
        pos = np.minimum(pos, self.V - 1)
        return np.where(self.hashes[pos] == h, pos, -1).astype(np.int32)

    def _csr(self, r, h, n):
        ids = self._ids(h)
        ptr = np.zeros(n + 1, np.int64)
        np.cumsum(np.bincount(r, minlength=n), out=ptr[1:])
        return ptr, ids


# ----------------------------------------------------------------------------
# Numba kernels
# ----------------------------------------------------------------------------
@njit(cache=True)
def _lev_sim(buf, a0, a1, b0, b1, prev, cur):
    la = a1 - a0
    lb = b1 - b0
    if la == 0 or lb == 0:
        return 0.0
    for j in range(lb + 1):
        prev[j] = j
    for i in range(1, la + 1):
        cur[0] = i
        ca = buf[a0 + i - 1]
        for j in range(1, lb + 1):
            cost = 0 if ca == buf[b0 + j - 1] else 1
            v = prev[j - 1] + cost
            d = prev[j] + 1
            if d < v:
                v = d
            ins = cur[j - 1] + 1
            if ins < v:
                v = ins
            cur[j] = v
        for j in range(lb + 1):
            prev[j] = cur[j]
    m = la if la > lb else lb
    return 1.0 - prev[lb] / m


@njit(cache=True)
def _is_prefix(buf, a0, a1, b0, b1):
    la = a1 - a0
    lb = b1 - b0
    n = la if la < lb else lb
    if n < 3:
        return False
    for k in range(n):
        if buf[a0 + k] != buf[b0 + k]:
            return False
    return True


N_TOKFEAT = 18


@njit(parallel=True, cache=True)
def token_feats(pq, pe, q_ptr, q_ids, e_ptr, e_ids, voc_ptr, voc_buf, idf, ratio, is_num,
                soft_thr):
    """Soft token alignment features for aligned pair arrays (pq[i], pe[i])."""
    n = pq.shape[0]
    out = np.full((n, N_TOKFEAT), np.nan, np.float32)
    nb = 1024
    bs = (n + nb - 1) // nb
    for b in prange(nb):
        prev = np.empty(64, np.int64)
        cur = np.empty(64, np.int64)
        esim = np.zeros(MAXTOK, np.float32)
        qpos = np.empty(MAXTOK, np.int64)
        for i in range(b * bs, min(n, (b + 1) * bs)):
            qa = q_ptr[pq[i]]
            qb = min(q_ptr[pq[i] + 1], qa + MAXTOK)
            ea = e_ptr[pe[i]]
            eb = min(e_ptr[pe[i] + 1], ea + MAXTOK)
            nq = qb - qa
            ne = eb - ea
            for k in range(ne):
                esim[k] = 0.0
            n_exact = 0
            n_soft = 0
            idf_match = 0.0
            idf_qun = 0.0
            max_qun = 0.0
            max_rq = -99.0
            sum_rq = 0.0
            n_marker = 0
            sim_sum = 0.0
            nm = 0
            for a in range(nq):
                ta = q_ids[qa + a]
                best = 0.0
                bestk = -1
                for k in range(ne):
                    tb = e_ids[ea + k]
                    if ta == tb and ta >= 0:
                        s = 1.0
                    elif ta < 0 or tb < 0 or is_num[ta] or is_num[tb]:
                        s = 0.0
                    else:
                        a0 = voc_ptr[ta]
                        a1 = voc_ptr[ta + 1]
                        b0 = voc_ptr[tb]
                        b1 = voc_ptr[tb + 1]
                        la = a1 - a0
                        lb = b1 - b0
                        mn = la if la < lb else lb
                        mx = la if la > lb else lb
                        s = 0.0
                        if mn >= 3 and (mx - mn) <= max(2, mx // 3):
                            s = _lev_sim(voc_buf, a0, a1, b0, b1, prev, cur)
                        if s < 0.8 and _is_prefix(voc_buf, a0, a1, b0, b1):
                            s = 0.8
                    if s > best:
                        best = s
                        bestk = k
                    if s > esim[k]:
                        esim[k] = s
                w = idf[ta] if ta >= 0 else 1.0
                if best >= 1.0:
                    n_exact += 1
                if best >= soft_thr:
                    n_soft += 1
                    idf_match += w * best
                    sim_sum += best
                    qpos[nm] = bestk
                    nm += 1
                else:
                    idf_qun += w
                    if w > max_qun:
                        max_qun = w
                    r = ratio[ta] if ta >= 0 else 0.0
                    if r > max_rq:
                        max_rq = r
                    if r > 0.0:
                        sum_rq += r
                    if r > 1.0:
                        n_marker += 1
            idf_eun = 0.0
            max_eun = 0.0
            max_re = -99.0
            n_esoft = 0
            for k in range(ne):
                tb = e_ids[ea + k]
                w = idf[tb] if tb >= 0 else 1.0
                if esim[k] >= soft_thr:
                    n_esoft += 1
                else:
                    idf_eun += w
                    if w > max_eun:
                        max_eun = w
                    r = ratio[tb] if tb >= 0 else 0.0
                    if r > max_re:
                        max_re = r
            inv = 0
            for x in range(nm):
                for y in range(x + 1, nm):
                    if qpos[y] < qpos[x]:
                        inv += 1
            first_match = 0.0
            if nq > 0 and ne > 0:
                ta = q_ids[qa]
                tb = e_ids[ea]
                if ta == tb and ta >= 0:
                    first_match = 1.0
            out[i, 0] = nq
            out[i, 1] = ne
            out[i, 2] = n_exact
            out[i, 3] = n_soft
            out[i, 4] = idf_match
            out[i, 5] = idf_qun
            out[i, 6] = idf_eun
            out[i, 7] = max_qun
            out[i, 8] = max_eun
            out[i, 9] = max_rq if max_rq > -99.0 else np.nan
            out[i, 10] = max_re if max_re > -99.0 else np.nan
            den = idf_match + idf_qun + idf_eun
            out[i, 11] = idf_match / den if den > 0 else np.nan
            out[i, 12] = n_soft / nq if nq > 0 else np.nan
            out[i, 13] = n_esoft / ne if ne > 0 else np.nan
            out[i, 14] = first_match
            out[i, 15] = inv / (nm * (nm - 1) / 2) if nm > 1 else 0.0
            out[i, 16] = sim_sum / nm if nm > 0 else np.nan
            out[i, 17] = n_marker + 0.001 * sum_rq
    return out


TOKFEAT_NAMES = ["nq", "ne", "exact", "soft", "idf_match", "idf_qun", "idf_eun", "max_idf_qun",
                 "max_idf_eun", "max_ratio_qun", "max_ratio_eun", "wjacc", "frac_q", "frac_e",
                 "first_match", "inversions", "mean_sim", "markers"]


@njit(cache=True)
def _behaviour_counts(q_rows, e_rows, q_ptr, q_ids, e_ptr, e_ids, hq, he, V):
    """Per token: occurrences as an extra word, and how many of them keep the house number
    (same), shift it upward by 1..BH_UP_MAX (up) or lack one (nohn)."""
    n = np.zeros(V, np.float64)
    same = np.zeros(V, np.float64)
    up = np.zeros(V, np.float64)
    nohn = np.zeros(V, np.float64)
    for i in range(q_rows.shape[0]):
        qa = q_ptr[q_rows[i]]
        qb = q_ptr[q_rows[i] + 1]
        ea = e_ptr[e_rows[i]]
        eb = e_ptr[e_rows[i] + 1]
        h1 = hq[q_rows[i]]
        h2 = he[e_rows[i]]
        rel = 0
        if h1 < 0 or h2 < 0:
            rel = 3
        elif h1 == h2:
            rel = 1
        elif h1 - h2 >= 1 and h1 - h2 <= BH_UP_MAX:
            rel = 2
        for a in range(qa, qb):
            t = q_ids[a]
            if t < 0:
                continue
            found = False
            for b in range(ea, eb):
                if e_ids[b] == t:
                    found = True
                    break
            if found:
                continue
            n[t] += 1.0
            if rel == 1:
                same[t] += 1.0
            elif rel == 2:
                up[t] += 1.0
            elif rel == 3:
                nohn[t] += 1.0
    return n, same, up, nohn


@njit(parallel=True, cache=True)
def behaviour_feats(pq, pe, q_ptr, q_ids, e_ptr, e_ids, same_r, up_r, nohn_r, known):
    """Behaviour of the record's extra words (w.r.t. this candidate): min same-rate, max
    up-rate, max nohn-rate over words with known behaviour, #known, #unknown extra words."""
    n = pq.shape[0]
    out = np.full((n, 5), np.nan, np.float32)
    for i in prange(n):
        qa = q_ptr[pq[i]]
        qb = q_ptr[pq[i] + 1]
        ea = e_ptr[pe[i]]
        eb = e_ptr[pe[i] + 1]
        mn_same = 2.0
        mx_up = -1.0
        mx_nohn = -1.0
        nk = 0
        nu = 0
        for a in range(qa, qb):
            t = q_ids[a]
            if t < 0:
                continue
            found = False
            for b in range(ea, eb):
                if e_ids[b] == t:
                    found = True
                    break
            if found:
                continue
            if known[t]:
                nk += 1
                if same_r[t] < mn_same:
                    mn_same = same_r[t]
                if up_r[t] > mx_up:
                    mx_up = up_r[t]
                if nohn_r[t] > mx_nohn:
                    mx_nohn = nohn_r[t]
            else:
                nu += 1
        if nk > 0:
            out[i, 0] = mn_same
            out[i, 1] = mx_up
            out[i, 2] = mx_nohn
        out[i, 3] = nk
        out[i, 4] = nu
    return out


@njit(parallel=True, cache=True)
def num_token_feats(pq, pe, q_ptr, q_ids, e_ptr, e_ids, is_num):
    """Exact agreement of numeric address tokens."""
    n = pq.shape[0]
    out = np.zeros((n, 5), np.float32)
    for i in prange(n):
        qa = q_ptr[pq[i]]
        qb = q_ptr[pq[i] + 1]
        ea = e_ptr[pe[i]]
        eb = e_ptr[pe[i] + 1]
        nqn = 0
        nen = 0
        m = 0
        for a in range(qa, qb):
            ta = q_ids[a]
            if ta < 0 or not is_num[ta]:
                continue
            nqn += 1
            for k in range(ea, eb):
                if e_ids[k] == ta:
                    m += 1
                    break
        for k in range(ea, eb):
            tb = e_ids[k]
            if tb >= 0 and is_num[tb]:
                nen += 1
        out[i, 0] = nqn
        out[i, 1] = nen
        out[i, 2] = m
        out[i, 3] = nqn - m
        out[i, 4] = nen - m
    return out


# ----------------------------------------------------------------------------
# universe
# ----------------------------------------------------------------------------
class Universe:
    def __init__(self, split: str):
        self.split = split
        with Timer(f"load universe {split}"):
            self.s1, self.q = load_universe(split, NORM_COLS)
        with Timer(f"token spaces {split}"):
            self.name_ts = TokenSpace(self.s1, self.q, "n_core", stat_col="n_all")
            self.legal_ts = TokenSpace(self.s1, self.q, "n_legal", stat_col="n_all")
            self.all_ts = TokenSpace(self.s1, self.q, "n_all")
            self.addr_ts = TokenSpace(self.s1, self.q, "a_tok")
        with Timer(f"universe stats {split}"):
            self._record_stats()

    def set_behaviour(self, cand: pl.DataFrame):
        """Word-behaviour rates of the name vocabulary from the record-argmax pairs of the
        candidate set (by pruner probability; labels are never used)."""
        best = (cand.select("q_row", "e_row", "p_prune")
                .sort(["q_row", "p_prune"], descending=[False, True])
                .unique(subset="q_row", keep="first"))
        hq = self.q["hn_num"].fill_null(-1).to_numpy().astype(np.int64)
        he = self.s1["hn_num"].fill_null(-1).to_numpy().astype(np.int64)
        ts = self.name_ts
        n, same, up, nohn = _behaviour_counts(
            best["q_row"].to_numpy().astype(np.int64), best["e_row"].to_numpy().astype(np.int64),
            ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids, hq, he, ts.V)
        rnd = lambda x: (np.round(x / np.maximum(n, 1.0) / BH_STEP) * BH_STEP).astype(np.float32)
        self.bh_same, self.bh_up, self.bh_nohn = rnd(same), rnd(up), rnd(nohn)
        self.bh_known = n >= BH_MIN_N
        log(f"word behaviour: {int(self.bh_known.sum())} words with >= {BH_MIN_N} extra-word occurrences")

    def _record_stats(self):
        s1, q = self.s1, self.q
        # derived strings used by rapidfuzz features
        extra = lambda df: df.with_columns(
            pl.col("n_core").str.replace_all(" ", "").alias("n_glued"),
            pl.col("a_loc").str.replace_all(r" \| ", " ").alias("a_locs"),
            pl.col("a_hn").str.extract(r"(\d+)", 1).cast(pl.Int64, strict=False).alias("hn_num"),
        )
        s1 = extra(s1)
        q = extra(q)
        # label-free universe statistics
        s1 = s1.with_columns(
            pl.len().over(["country", "n_core"]).alias("u_s1_same_name"),
            pl.len().over(["country", "a_tok"]).alias("u_s1_same_addr"),
            pl.len().over(["country", "a_hn", "a_street"]).alias("u_s1_same_hnst"),
        )
        name_cnt = s1.group_by(["country", "n_core"]).len().rename({"len": "u_q_s1_same_name"})
        q = q.join(name_cnt, on=["country", "n_core"], how="left").with_columns(
            pl.col("u_q_s1_same_name").fill_null(0))
        q = q.with_columns(pl.len().over(["country", "n_core", "a_tok"]).alias("u_q_dups"))
        self.s1 = s1.sort("row")
        self.q = q.sort("row")
        # 64-bit hashes of fields for O(1) equality features
        self.hq, self.he = {}, {}
        for c in ("a_hn", "a_street", "n_core", "n_glued", "a_tok", "n_legal", "a_state", "a_locs"):
            self.hq[c] = self.q[c].hash(seed=3).to_numpy()
            self.he[c] = self.s1[c].hash(seed=3).to_numpy()
            self.hq[c + "_empty"] = (self.q[c] == "").to_numpy()
            self.he[c + "_empty"] = (self.s1[c] == "").to_numpy()


# ----------------------------------------------------------------------------
# pair features
# ----------------------------------------------------------------------------
def _rf(scorer, a, b, **kw):
    return process.cpdist(a, b, scorer=scorer, workers=-1, dtype=np.float32, **kw)


NF_BITS = {"alias": 1, "domain": 2, "handle": 4, "id": 8, "phone": 16, "honor": 32, "pipe": 64,
           "upper": 128, "ocr": 256, "inv": 512, "seg": 1024}
AF_BITS = {"missing": 1, "null": 2, "pobox": 4, "pmb": 8, "unit": 16, "reorder": 32, "nohn": 64,
           "hash": 128, "range": 256, "half": 512, "indic": 1024}


def pair_features(U: Universe, cand: pl.DataFrame) -> pl.DataFrame:
    """cand: q_row, e_row, score, rank (+ anything else, passed through)."""
    pq = cand["q_row"].to_numpy().astype(np.int64)
    pe = cand["e_row"].to_numpy().astype(np.int64)
    F = {}
    # --- token alignment -----------------------------------------------------
    ts = U.name_ts
    tf = token_feats(pq, pe, ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids, ts.voc_ptr, ts.voc_buf,
                     ts.idf, ts.ratio, ts.is_num, 0.75)
    for k, nm in enumerate(TOKFEAT_NAMES):
        F["nt_" + nm] = tf[:, k]
    ts = U.legal_ts
    lf = token_feats(pq, pe, ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids, ts.voc_ptr, ts.voc_buf,
                     ts.idf, ts.ratio, ts.is_num, 0.99)
    for k in (0, 1, 2):
        F["lg_" + TOKFEAT_NAMES[k]] = lf[:, k]
    F["lg_q_subset"] = ((lf[:, 2] == lf[:, 0]) & (lf[:, 0] < lf[:, 1])).astype(np.float32)
    ts = U.all_ts
    nf_ = token_feats(pq, pe, ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids, ts.voc_ptr, ts.voc_buf,
                      ts.idf, ts.ratio, ts.is_num, 0.75)
    for k in (9, 10, 17):
        F["na_" + TOKFEAT_NAMES[k]] = nf_[:, k]
    ts = U.addr_ts
    af = token_feats(pq, pe, ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids, ts.voc_ptr, ts.voc_buf,
                     ts.idf, ts.ratio, ts.is_num, 0.8)
    for k, nm in enumerate(TOKFEAT_NAMES):
        if nm in ("markers", "inversions"):
            continue
        F["at_" + nm] = af[:, k]
    nf = num_token_feats(pq, pe, ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids, ts.is_num)
    for k, nm in enumerate(["nq", "ne", "match", "qun", "eun"]):
        F["an_" + nm] = nf[:, k]
    ts = U.name_ts
    bf = behaviour_feats(pq, pe, ts.q_ptr, ts.q_ids, ts.s1_ptr, ts.s1_ids,
                         U.bh_same, U.bh_up, U.bh_nohn, U.bh_known)
    for k, nm in enumerate(["min_same", "max_up", "max_nohn", "n_known", "n_unknown"]):
        F["bh_" + nm] = bf[:, k]

    # --- aligned record columns ---------------------------------------------
    qcols = ["n_core", "n_all", "n_alt", "n_glued", "n_legal", "a_all", "a_tok", "a_hn", "a_hnsfx",
             "a_street", "a_locs", "a_state", "a_unit", "hn_num", "n_flags", "a_flags", "n_indic",
             "n_indic_hit", "src", "u_q_s1_same_name", "u_q_dups"]
    ecols = ["n_core", "n_all", "n_glued", "n_legal", "a_all", "a_tok", "a_hn", "a_hnsfx",
             "a_street", "a_locs", "a_state", "a_unit", "hn_num", "n_flags", "a_flags",
             "u_s1_same_name", "u_s1_same_addr", "u_s1_same_hnst"]
    Q = U.q.select(qcols)[pq]
    E = U.s1.select(ecols)[pe]
    lst = lambda df, c: df[c].to_list()

    qn, en = lst(Q, "n_core"), lst(E, "n_core")
    F["rf_n_ratio"] = _rf(fuzz.ratio, qn, en)
    F["rf_n_tset"] = _rf(fuzz.token_set_ratio, qn, en)
    F["rf_n_tsort"] = _rf(fuzz.token_sort_ratio, qn, en)
    F["rf_n_partial"] = _rf(fuzz.partial_ratio, qn, en)
    F["rf_n_jw"] = _rf(JaroWinkler.normalized_similarity, qn, en)
    qg, eg = lst(Q, "n_glued"), lst(E, "n_glued")
    F["rf_g_ratio"] = _rf(fuzz.ratio, qg, eg)
    F["rf_g_partial"] = _rf(fuzz.partial_ratio, qg, eg)
    F["rf_nall_tset"] = _rf(fuzz.token_set_ratio, lst(Q, "n_all"), lst(E, "n_all"))
    qalt = lst(Q, "n_alt")
    alt = _rf(fuzz.token_set_ratio, qalt, en)
    alt[np.array([not s for s in qalt])] = np.nan
    F["rf_alt_tset"] = alt
    qa, ea = lst(Q, "a_tok"), lst(E, "a_tok")
    F["rf_a_ratio"] = _rf(fuzz.ratio, lst(Q, "a_all"), lst(E, "a_all"))
    F["rf_a_tset"] = _rf(fuzz.token_set_ratio, qa, ea)
    F["rf_a_tsort"] = _rf(fuzz.token_sort_ratio, qa, ea)
    F["rf_a_partial"] = _rf(fuzz.partial_ratio, qa, ea)
    qs, es = lst(Q, "a_street"), lst(E, "a_street")
    F["rf_st_ratio"] = _rf(fuzz.ratio, qs, es)
    F["rf_st_tset"] = _rf(fuzz.token_set_ratio, qs, es)
    F["rf_st_jw"] = _rf(JaroWinkler.normalized_similarity, qs, es)
    ql, el = lst(Q, "a_locs"), lst(E, "a_locs")
    F["rf_loc_tset"] = _rf(fuzz.token_set_ratio, ql, el)
    F["rf_loc_partial"] = _rf(fuzz.partial_ratio, ql, el)
    qh, eh = lst(Q, "a_hn"), lst(E, "a_hn")
    F["hn_lev"] = _rf(Levenshtein.distance, qh, eh)
    F["hn_indel"] = _rf(Indel.distance, qh, eh)

    # mask string similarities where one side is empty
    def empty(df, c):
        return (df[c] == "").to_numpy()
    for key, col in [("rf_n_", "n_core"), ("rf_g_", "n_glued"), ("rf_a_", "a_tok"),
                     ("rf_st_", "a_street"), ("rf_loc_", "a_locs")]:
        m = empty(Q, col) | empty(E, col)
        for f in list(F):
            if f.startswith(key):
                F[f][m] = np.nan
    hq_e, he_e = empty(Q, "a_hn"), empty(E, "a_hn")
    hn_missing = hq_e | he_e
    for f in ("hn_lev", "hn_indel"):
        F[f][hn_missing] = np.nan

    # --- house numbers -----------------------------------------------------------
    hq = Q["hn_num"].to_numpy().astype(np.float64)
    he = E["hn_num"].to_numpy().astype(np.float64)
    both = ~np.isnan(hq) & ~np.isnan(he)
    F["hn_q_present"] = (~hq_e).astype(np.float32)
    F["hn_e_present"] = (~he_e).astype(np.float32)
    F["hn_str_eq"] = np.where(hn_missing, np.nan, (Q["a_hn"] == E["a_hn"]).to_numpy()).astype(np.float32)
    d = np.abs(hq - he)
    F["hn_absdiff"] = np.where(both, np.minimum(d, 1e6), np.nan).astype(np.float32)
    F["hn_signdiff"] = np.where(both, np.clip(hq - he, -1e6, 1e6), np.nan).astype(np.float32)
    F["hn_reldiff"] = np.where(both, d / np.maximum(np.maximum(hq, he), 1), np.nan).astype(np.float32)
    lq = Q["a_hn"].str.len_chars().to_numpy().astype(np.float32)
    le = E["a_hn"].str.len_chars().to_numpy().astype(np.float32)
    F["hn_lendiff"] = np.where(hn_missing, np.nan, lq - le)
    indel = F["hn_indel"]
    F["hn_subseq"] = np.where(hn_missing, np.nan,
                              ((indel == np.abs(lq - le)) & (lq != le)).astype(np.float32))
    fq = Q["a_hn"].str.slice(0, 1)
    fe = E["a_hn"].str.slice(0, 1)
    F["hn_first_eq"] = np.where(hn_missing, np.nan, (fq == fe).to_numpy()).astype(np.float32)
    lq_ = Q["a_hn"].str.slice(-1, 1)
    le_ = E["a_hn"].str.slice(-1, 1)
    F["hn_last_eq"] = np.where(hn_missing, np.nan, (lq_ == le_).to_numpy()).astype(np.float32)
    sq_, se_ = Q["a_hnsfx"], E["a_hnsfx"]
    F["hn_sfx_q"] = (sq_ != "").to_numpy().astype(np.float32)
    F["hn_sfx_e"] = (se_ != "").to_numpy().astype(np.float32)
    F["hn_sfx_eq"] = ((sq_ == se_) & (sq_ != "")).to_numpy().astype(np.float32)

    # --- state / unit / legal -------------------------------------------------------
    stq, ste = Q["a_state"], E["a_state"]
    F["state_eq"] = np.where(((stq == "") | (ste == "")).to_numpy(), np.nan,
                             (stq == ste).to_numpy()).astype(np.float32)
    F["unit_q"] = (Q["a_unit"] != "").to_numpy().astype(np.float32)
    F["unit_e"] = (E["a_unit"] != "").to_numpy().astype(np.float32)
    F["unit_eq"] = ((Q["a_unit"] == E["a_unit"]) & (Q["a_unit"] != "")).to_numpy().astype(np.float32)
    F["legal_eq"] = (Q["n_legal"] == E["n_legal"]).to_numpy().astype(np.float32)
    F["legal_q_empty"] = (Q["n_legal"] == "").to_numpy().astype(np.float32)
    F["legal_e_empty"] = (E["n_legal"] == "").to_numpy().astype(np.float32)

    # --- flags -------------------------------------------------------------------
    qnf = Q["n_flags"].to_numpy()
    enf = E["n_flags"].to_numpy()
    qaf = Q["a_flags"].to_numpy()
    eaf = E["a_flags"].to_numpy()
    for k, bit in NF_BITS.items():
        F["qnf_" + k] = ((qnf & bit) > 0).astype(np.float32)
    for k in ("inv", "honor", "upper"):
        F["enf_" + k] = ((enf & NF_BITS[k]) > 0).astype(np.float32)
    for k, bit in AF_BITS.items():
        F["qaf_" + k] = ((qaf & bit) > 0).astype(np.float32)
    for k in ("reorder", "unit", "nohn", "missing"):
        F["eaf_" + k] = ((eaf & AF_BITS[k]) > 0).astype(np.float32)
    ni = Q["n_indic"].to_numpy().astype(np.float32)
    F["q_indic"] = ni
    F["q_indic_miss"] = ni - Q["n_indic_hit"].to_numpy().astype(np.float32)
    F["q_src"] = Q["src"].to_numpy().astype(np.float32)
    F["q_nlen"] = Q["n_core"].str.len_chars().to_numpy().astype(np.float32)
    F["e_nlen"] = E["n_core"].str.len_chars().to_numpy().astype(np.float32)
    F["q_alen"] = Q["a_tok"].str.len_chars().to_numpy().astype(np.float32)
    F["e_alen"] = E["a_tok"].str.len_chars().to_numpy().astype(np.float32)
    # --- universe stats ------------------------------------------------------------
    for c in ("u_q_s1_same_name", "u_q_dups"):
        F[c] = np.minimum(Q[c].to_numpy(), U_CAP).astype(np.float32)
    for c in ("u_s1_same_name", "u_s1_same_addr", "u_s1_same_hnst"):
        F[c] = np.minimum(E[c].to_numpy(), U_CAP).astype(np.float32)
    # --- retrieval (two channels) -----------------------------------------------------
    for col in ("s_all", "r_all", "s_addr", "r_addr"):
        F["ret_" + col] = cand[col].cast(pl.Float32).to_numpy()
    F["ret_rel_all"] = (cand["s_all"] / cand["top_all"]).cast(pl.Float32).to_numpy()
    F["ret_rel_addr"] = (cand["s_addr"] / cand["top_addr"]).cast(pl.Float32).to_numpy()
    F["ret_ncand"] = cand.select(pl.len().over("q_row")).to_series().to_numpy().astype(np.float32)

    out = pl.DataFrame({k: np.asarray(v, dtype=np.float32) for k, v in F.items()})
    return out
